levelfive/appfive/urls.py
from django.urls import path
from appfive import views

# template urls

app_name = 'appfive'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login',views.user_login,name='user_login'),
]

levelfive/levelfive/urls.py
from django.contrib import admin
from django.urls import path,include
from appfive import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('appfive/',include('appfive.urls')),
    path('logout/',views.user_logout,name="logout"),
    path('special/',views.special,name='special'),
]

levelfive/appfive/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserprofileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

levelfive/appfive/forms.py
from django import forms
from django.contrib.auth.models import User
from appfive.models import UserprofileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserprofileInfoFrom(forms.ModelForm):
    class Meta():
        model = UserprofileInfo
        fields = ('portfolio_site', 'profile_pic')

levelfive/appfive/views.py
from django.shortcuts import render
from appfive.forms import UserprofileInfoFrom,UserForm

# 
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse 
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'appfive/index.html')

@login_required
def special(request):
    return HttpResponse("you are logged in , Nice")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserprofileInfoFrom(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserprofileInfoFrom()

    return render(request,'appfive/registration.html',
                        {'user_form':user_form,'profile_form':profile_form,
                        'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("someone tried to login and failed")
            print(f"username: {username} and password: {password}")
            return HttpResponse("invalid login details supplied")
    else:
        return render(request,'appfive/login.html', {})

levelfive/templates/appfive/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index'%}" class="navbar-brand">DJANGO</a></li>
                <li><a href="{% url 'admin:index'%}" class="navbar-link">Admin</a></li>
                <li><a href="{% url 'appfive:register'%}" class="navbar-link">Register</a></li>
                
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="navbar-link">Logout</a></li>
                {% else %}
                <li><a href="{% url 'appfive:user_login' %}" class="navbar-link">Login</a></li>
                {% endif %}


            </ul>
        </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>  
</body>
</html>

levelfive/templates/appfive/index.html
{% extends "appfive/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django level Five</h1>
</div>

{% endblock %}

levelfive/templates/appfive/login.html
{% extends "appfive/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>please login</h1>
    <form action="{% url 'appfive:user_login'%}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="enter username">

        <label for="password">Password:</label>
        <input type="password" name="password" >

        <input type="submit" name="" value="Login">
    </form>
</div>


{% endblock %}

levelfive/templates/appfive/registration.html
{% extends "appfive/base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
       <h1>thank you for registering</h1>
    {% else %}
        <h1>Register here</h1>
        <h3>fill out the form</h3>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
    {% endif %}
</div>

{% endblock%}